name "banner"
html `
<div class="hy flex horizontal center center-text banner" style="margin-top: 6em;">
	<div style="width: max-content; height: max-content;">
		<img src="{{@image:res/img/logo-v1b.png}}" width="40%" style="min-width: 12em; max-width: 18em; aspect-ratio: 1;">
	</div>
	<div style="width: 4em;"></div>
	<div class="hy flex vertical center center-text">
		<h1 class="hy flex vertical center center-text no-color" style="box-shadow: none;">
			Anima Runtime
		</h1>
		<span class="hy flex vertical center center-text no-color" style="box-shadow: none; margin-top: -2em; margin-bottom: 1em; font-weight: normal; font-size: 1.2em;">
			A modern virtual machine for modern languages
		</span>
		<div class="hy flex horizontal center center-text" style="height: 3em;">
			<a class="hy button action" href="tutorial.html" style="width: 60%;">
				Getting Started
			</a>
		</div>
	</div>
</div>
`
