name nav-sidebar

html_begin `
<div class="hy sidebar">
<div class="hy display">
<h1
    class="hy flex vertical center no-color"
    style="box-shadow: none; margin: -0.6em 0.3em"
>
    <<link to={{root}}>>
    <h1
        class="hy flex vertical center no-color"
        style="box-shadow: none; margin: -0.6em 0.3em"
    >
        {{title}}
    </h1>
    <</link>>
</h1>
<hr class="hy" />
<div class="hy">
`

html_end `
</div>
</div>
</div>
`
